PRN221_Project_ShopOnline/PRN221_Project_ShopOnline/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using PRN221_Project_ShopOnline.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using PRN221_Project_ShopOnline.DAO;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Text.Json;
using System.Security.Cryptography;

namespace PRN221_Project_ShopOnline.Controllers
{
    public class DefaultController : Controller
    {
        private readonly HttpClient client = null;
        private string url = "";
        private string urlc = "";
        public DefaultController()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            url = "https://localhost:7007/product";
            urlc = "https://localhost:7007/category";
        }
        public async Task<ActionResult> Index()
        {
            var view = View("Views/Index.cshtml");
            var response = await client.GetAsync(url);
            var json = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var  products= JsonSerializer.Deserialize<List<Product>>(json, options);
            var responsec = await client.GetAsync(urlc);
            var jsonc = await responsec.Content.ReadAsStringAsync();
            var optionsc = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var categories = JsonSerializer.Deserialize<List<Category>>(jsonc, optionsc);
            //set to ViewBag
            ViewBag.Categories = categories;
            ViewBag.Products = products;
            //no selected category
            ViewBag.SelectedCategory = 0;

            return view;
        }

        public async Task<ActionResult> FindProductByCategory(int cid)
        {
            var view = View("Views/Index.cshtml");

            //Get list Category
            var responsec = await client.GetAsync(urlc);
            var jsonc = await responsec.Content.ReadAsStringAsync();
            var optionsc = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var categories = JsonSerializer.Deserialize<List<Category>>(jsonc, optionsc);
            //Get list Products by Category
            var response = await client.GetAsync(url+"/categoryId/"+cid);
            var json = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var products = JsonSerializer.Deserialize<List<Product>>(json, options);

            //set to ViewBag
            ViewBag.Categories = categories;
            ViewBag.Products = products;
            //Selected Category (for different display)
            ViewBag.SelectedCategory = cid;

            return view;
        }

        public async Task<ActionResult> SearchProductByName(string ProductName)
        {
            var view = View("Views/Index.cshtml");

            //Get list Category
            var responsec = await client.GetAsync(urlc);
            var jsonc = await responsec.Content.ReadAsStringAsync();
            var optionsc = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var categories = JsonSerializer.Deserialize<List<Category>>(jsonc, optionsc);

            //Get list Products by Name
            var response = await client.GetAsync(url + "/productname/" + ProductName);
            var json = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var products = JsonSerializer.Deserialize<List<Product>>(json, options);

            //set to ViewBag
            ViewBag.Categories = categories;
            ViewBag.Products = products;
            //no selected category
            ViewBag.SelectedCategory = 0;

            return view;
        }
    }
}

PRN221_Project_ShopOnline/PRN221_Project_ShopOnline/Views/Shared/MenuBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@* for Session *@
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!--Logo-->
        <a class="navbar-brand" href="/">
            <img src="/image/Other/Logo.jpg" id="logo" style="width: 200px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!--Login: only show if user is not login -> check Session-->
                @if (httpContextAccessor.HttpContext.Session.GetString("userId") == null)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="/Login">Login</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <!--Cart-->
                        <a class="btn btn-info" href="/Cart/Index">
                            <i class="fa fa-shopping-cart"></i> Cart
                            @*<span class="badge bg-secondary" id="CartNum">5</span>*@
                        </a>
                    </li>

                    //if user is login
                    //show Message
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Hello @httpContextAccessor.HttpContext.Session.GetString("username")
                        </a>
                    </li>

                    //if user is Seller
                    @if (httpContextAccessor.HttpContext.Session.GetInt32("isSeller") == 1)
                    {
                        //Manage Product link
                        <li class="nav-item">
                            <a class="nav-link" href="/ProductManager/Index">
                                Manage Product
                            </a>
                        </li>
                    }

                    //if user is Admin
                    @if (httpContextAccessor.HttpContext.Session.GetInt32("isAdmin") == 1)
                    {
                        //Manage Account link
                        <li class="nav-item">
                            <a class="nav-link" href="/AccountManager/Index">
                                Manage Account
                            </a>
                        </li>

                        //Dashboard link (unsupported)
                        <li class="nav-item">
                            <a class="nav-link" href="/Dashboard/Index">
                                Dashboard
                            </a>
                        </li>
                    }

                    //logout link
                    <li class="nav-item">
                        <a class="nav-link" href="/Login/Logout">
                            Log out
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

PRN221_Project_ShopOnline/PRN221_Project_ShopOnline/Views/Shared/MenuBarWithSearch.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@* for Session *@
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!--Logo-->
        <a class="navbar-brand" href="/">
            <img src="/image/Other/Logo.jpg" id="logo" style="width: 200px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!--Login: only show if user is not login -> check Session-->
                @if (httpContextAccessor.HttpContext.Session.GetString("userId") == null)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="/Login">Login</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <!--Cart-->
                        <a class="btn btn-info" href="/Cart/Index">
                            <i class="fa fa-shopping-cart"></i> Cart
                            @*<span class="badge bg-secondary" id="CartNum">5</span>*@
                        </a>
                    </li>

                    //if user is login
                    //show Message
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Hello @httpContextAccessor.HttpContext.Session.GetString("username")
                        </a>
                    </li>

                    //if user is Seller
                    @if (httpContextAccessor.HttpContext.Session.GetInt32("isSeller") == 1)
                    {
                        //Manage Product link
                        <li class="nav-item">
                            <a class="nav-link" href="/ProductManager/Index">
                                Manage Product
                            </a>
                        </li>
                    }

                    //if user is Admin
                    @if (httpContextAccessor.HttpContext.Session.GetInt32("isAdmin") == 1)
                    {
                        //Manage Account link
                        <li class="nav-item">
                            <a class="nav-link" href="/AccountManager/Index">
                                Manage Account
                            </a>
                        </li>

                        //Dashboard link (unsupported)
                        <li class="nav-item">
                            <a class="nav-link" href="/Dashboard/Index">
                                Dashboard
                            </a>
                        </li>
                    }

                    //logout link
                    <li class="nav-item">
                        <a class="nav-link" href="/Login/Logout">
                            Log out
                        </a>
                    </li>
                }
            </ul>
            <!--Search-->
            @using (Html.BeginForm("SearchProductByName", "Default", FormMethod.Post))
            {
                <input class="form-control me-2" type="search" placeholder="Search"
                       aria-label="Search" name="ProductName" id="searchBar">
                <button class="btn btn-outline-success" type="submit" id="searchButton">Search</button>
            }
        </div>
    </div>
</nav>